import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const departure = localFont({
  src: "./fonts/DepartureMono-Regular.woff",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"text-balance w-full h-full bg-background text-foreground flex justify-center "}
      >
        {children}
      </body>
    </html>
  );
}
